OP-22745: Build Medusa Docker image
c3-e/cassandra-medusa pull request #1
Opened 2021-05-28 22:37 UTC by c3-danmerino

2021-05-29 20:23 UTC, c3-amitsalunke commented
@c3-danmerino - Lets create epic branch to deliver all changes.

2021-05-29 20:23 UTC, c3-amitsalunke requested changes

2021-05-29 20:23 UTC, c3-amitsalunke commented on k8s/files/c3/cassandra/basic_test_v3.yaml
> +keyspace: stresscql
we should be packing this file

2021-05-29 20:23 UTC, c3-amitsalunke commented on k8s/files/etc/medusa/medusa.ini
> +[cassandra]
How this file being used?

2021-06-01 16:26 UTC, c3-danmerino commented on k8s/files/etc/medusa/medusa.ini
> +[cassandra]
this is Medusa config. defines storage location, bucket, name of credential secrets and other options

2021-06-01 16:28 UTC, c3-danmerino commented on k8s/files/c3/cassandra/basic_test_v3.yaml
> +keyspace: stresscql
what do you mean by this?

2021-06-09 16:30 UTC, merged